name : Deploy to Staging
on: 
  push:
    branches: [ main ]

jobs: 
  redeploy_evrything:
    runs-on: ubuntu-latest
    name: Deploying evrything to the staging cluster
    steps:
    - run: |
       echo {{ secrets.SSH_PRIVATE_KEY }} &> ~/ssh_key 
       echo {{ secrets.KNOWN_HOSTS }} &> ~/.ssh/knows_hosts
       ssh -i ~/ssh_key ubuntu@98.82.10.211
       cd ci-cd-deployment/ && git pull
       pnpm install 
       pnpm run build
       pnpm restart web-server
       pnpm restart fe-server
       pnpm restart socket-server
       EOF
