name: Deploy to Staging

on: 
  push:
    branches: [ main ]

jobs: 
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - name: Setup SSH Key and Disable Host Checking
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: SSH and Deploy
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@98.82.10.211 << 'EOF'
            cd ci-cd-deployment/
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pnpm install
            pnpm run build
            pm2 restart web-server
            pm2 restart http-server
            pm2 restart  ws-server
          EOF
